version: '3.8'

services:
  biocontrol_app:
    build: .
    container_name: Process_Simulator
    ports:
      - "8501:8501"
    volumes:
      # Sincroniza el código local con el contenedor.
      # Así, si editas un archivo .py, el contenedor se actualiza sin tener que reconstruirlo.
      - .:/app
      
      # Si generas archivos LaTeX (.tex), PDFs o datos (.npz) desde el código,
      # esto asegura que se guarden en tu máquina host de forma persistente.
      # Descomenta la siguiente línea si usas una carpeta específica para reportes:
      # - ./Output:/app/Output
    environment:
      - PYTHONUNBUFFERED=1
      # Las siguientes líneas solucionan el problema de la pantalla gris de carga
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false